os: windows

language: node_js
node_js: 10

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(?:-\w+)?$/

script:
  - npm run build

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file_glob: true
  file: "build/*.exe"
  skip_cleanup: true
  on:
    tags: true
  draft: true
